[PRODUCTION] 
    DMCP_KEYHANDLER_URL = 'http://127.0.0.1:8002'
    DMCP_KEYHANDLER_PASSWORD = 'change_me'
    EMAIL_REMOVER_URL = '127.0.0.1:8001'
    EMAIL_REMOVER_PASSWORD = 'change_me'
    OPENPGP_KEYHANDLER_URL = 'http://127.0.0.1:8003'
    OPENPGP_KEYHANDLER_PASSWORD = 'change_me'
    SECRET_KEY = 'change_me'
    WTF_CSRF_SECRET_KEY = 'change_me'
    SQLALCHEMY_DATABASE_URI = 'mysql://mail_rw:change_me@127.0.0.1/mail'
    SQLALCHEMY_DATABASE_URI = None
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    WTF_CSRF_SECRET_KEY = 'change_me'
    MX_RECORD_PRIORITY = 10
    MX_RECORD_HOST = 'mail.ddmail.se.'
    SPF_RECORD = '"v=spf1 mx -all"'
    DKIM_RECORD = '"v=DKIM1; k=rsa;  \\\\009p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoxbFCUM83lUvHKku3mE/IOb2LArgPsjzhijO4pZfVLrLp7dv8RKDs4MmtFHrdWf4UibDFZtPm4IKcagDD3LlqgPSeewnfesI/kGCdz2SqPA/R5Cip5I1swtQ1lKa41eu6Rxym32fzCrRAhBfOZqM05BKPQQpxcSuyNmKOz+HGlGtkUMk5ebhWDtTsoc7ntw\" \"nhnAxaF+T61YQdYyCL \\\\009P7l6KRULaDJ3U7AkNAYrXpv0AdfjDVZp+GXu5fqTFTMi5pYGv1pj4621OSysDmjFlPksCgDouE11N+sJVCVPj//8gJCpzDv7y2kET9MIPmIlKGBTC1AQg5KWrbkeQPcEnzhRwIDAQAB"'
    DMARC_RECORD = '"v=DMARC1; p=none"'

[TESTING]
    DMCP_KEYHANDLER_URL = 'http://127.0.0.1:8002'
    DMCP_KEYHANDLER_PASSWORD = 'change_me'
    EMAIL_REMOVER_URL = '127.0.0.1:8001'
    EMAIL_REMOVER_PASSWORD = 'change_me'
    OPENPGP_KEYHANDLER_URL = 'http://127.0.0.1:8003'
    OPENPGP_KEYHANDLER_PASSWORD = 'change_me'
    SECRET_KEY = 'change_me'
    WTF_CSRF_SECRET_KEY = 'change_me'
    SQLALCHEMY_DATABASE_URI = 'mysql://mail_rw:change_me@127.0.0.1/mail_test'
    SQLALCHEMY_DATABASE_URI = None
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    WTF_CSRF_SECRET_KEY = 'change_me'
    MX_RECORD_PRIORITY = 10
    MX_RECORD_HOST = 'mail.ddmail.se.'
    SPF_RECORD = '"v=spf1 mx -all"'
    DKIM_RECORD = '"v=DKIM1; k=rsa;  \\\\009p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoxbFCUM83lUvHKku3mE/IOb2LArgPsjzhijO4pZfVLrLp7dv8RKDs4MmtFHrdWf4UibDFZtPm4IKcagDD3LlqgPSeewnfesI/kGCdz2SqPA/R5Cip5I1swtQ1lKa41eu6Rxym32fzCrRAhBfOZqM05BKPQQpxcSuyNmKOz+HGlGtkUMk5ebhWDtTsoc7ntw\" \"nhnAxaF+T61YQdYyCL \\\\009P7l6KRULaDJ3U7AkNAYrXpv0AdfjDVZp+GXu5fqTFTMi5pYGv1pj4621OSysDmjFlPksCgDouE11N+sJVCVPj//8gJCpzDv7y2kET9MIPmIlKGBTC1AQg5KWrbkeQPcEnzhRwIDAQAB"'
    DMARC_RECORD = '"v=DMARC1; p=none"'

[DEVELOPMENT]
    DMCP_KEYHANDLER_URL = 'http://127.0.0.1:8002'
    DMCP_KEYHANDLER_PASSWORD = 'change_me'
    EMAIL_REMOVER_URL = '127.0.0.1:8001'
    EMAIL_REMOVER_PASSWORD = 'change_me'
    OPENPGP_KEYHANDLER_URL = 'http://127.0.0.1:8003'
    OPENPGP_KEYHANDLER_PASSWORD = 'change_me'
    SECRET_KEY = 'change_me'
    WTF_CSRF_SECRET_KEY = 'change_me'
    SQLALCHEMY_DATABASE_URI = 'mysql://mail_rw:change_me@127.0.0.1/mail_dev'
    SQLALCHEMY_DATABASE_URI = None
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    WTF_CSRF_SECRET_KEY = 'change_me'
    MX_RECORD_PRIORITY = 10
    MX_RECORD_HOST = 'mail.ddmail.se.'
    SPF_RECORD = '"v=spf1 mx -all"'
    DKIM_RECORD = '"v=DKIM1; k=rsa;  \\\\009p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoxbFCUM83lUvHKku3mE/IOb2LArgPsjzhijO4pZfVLrLp7dv8RKDs4MmtFHrdWf4UibDFZtPm4IKcagDD3LlqgPSeewnfesI/kGCdz2SqPA/R5Cip5I1swtQ1lKa41eu6Rxym32fzCrRAhBfOZqM05BKPQQpxcSuyNmKOz+HGlGtkUMk5ebhWDtTsoc7ntw\" \"nhnAxaF+T61YQdYyCL \\\\009P7l6KRULaDJ3U7AkNAYrXpv0AdfjDVZp+GXu5fqTFTMi5pYGv1pj4621OSysDmjFlPksCgDouE11N+sJVCVPj//8gJCpzDv7y2kET9MIPmIlKGBTC1AQg5KWrbkeQPcEnzhRwIDAQAB"'
    DMARC_RECORD = '"v=DMARC1; p=none"'

